version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: fast-feet-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=delivery-api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: